package gaming.dsr.uwyg.equipment.definition;

import gaming.dsr.uwyg.equipment.types.BaseEquipmentDefinition;
import gaming.dsr.uwyg.equipment.types.enums.EquipmentCategory;
import gaming.dsr.uwyg.equipment.types.enums.ItemUpgradePath;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

@SuppressWarnings("ALL")
public final class EquipmentDefinitionTables {

    public static final int BASE_ITEM_ID_MELEE_PARRYING_DAGGER = 101000;
    public static final int BASE_ITEM_ID_MELEE_DARK_HAND = 904000;
    public static final int BASE_ITEM_ID_SHIELD_SKULL_LANTERN = 1396000;
    public static final int BASE_ITEM_ID_RING_COVENANT_OF_ARTORIAS = 138;
    public static final int BASE_ITEM_ID_RING_ORANGE_CHARRED = 139;

    private static final Map<Integer, BaseEquipmentDefinition> ARMOR_BY_BASE_ID;
    private static final Map<Integer, BaseEquipmentDefinition> MELEE_WEAPON_BY_BASE_ID;
    private static final Map<Integer, BaseEquipmentDefinition> RANGED_WEAPON_BY_BASE_ID;
    private static final Map<Integer, BaseEquipmentDefinition> SHIELD_BY_BASE_ID;
    private static final Map<Integer, BaseEquipmentDefinition> SPELL_TOOL_BY_BASE_ID;
    private static final Map<Integer, BaseEquipmentDefinition> SPELL_BY_BASE_ID;
    private static final Map<Integer, BaseEquipmentDefinition> RING_BY_BASE_ID;

    static {
        Map<Integer, BaseEquipmentDefinition> armor = new HashMap<>();
        Map<Integer, BaseEquipmentDefinition> melee = new HashMap<>();
        Map<Integer, BaseEquipmentDefinition> ranged = new HashMap<>();
        Map<Integer, BaseEquipmentDefinition> shield = new HashMap<>();
        Map<Integer, BaseEquipmentDefinition> spellTools = new HashMap<>();
        Map<Integer, BaseEquipmentDefinition> spells = new HashMap<>();
        Map<Integer, BaseEquipmentDefinition> rings = new HashMap<>();

        put(armor, EquipmentCategory.ARMOR, 10000, 1, ItemUpgradePath.UNIQUE, "Catarina Helm");
        put(armor, EquipmentCategory.ARMOR, 11000, 1, ItemUpgradePath.UNIQUE, "Catarina Armor");
        put(armor, EquipmentCategory.ARMOR, 12000, 1, ItemUpgradePath.UNIQUE, "Catarina Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 13000, 1, ItemUpgradePath.UNIQUE, "Catarina Leggings");
        put(armor, EquipmentCategory.ARMOR, 20000, 1, ItemUpgradePath.UNIQUE, "Paladin Helm");
        put(armor, EquipmentCategory.ARMOR, 21000, 1, ItemUpgradePath.UNIQUE, "Paladin Armor");
        put(armor, EquipmentCategory.ARMOR, 22000, 1, ItemUpgradePath.UNIQUE, "Paladin Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 23000, 1, ItemUpgradePath.UNIQUE, "Paladin Leggings");
        put(armor, EquipmentCategory.ARMOR, 40000, 1, ItemUpgradePath.UNIQUE, "Dark Mask");
        put(armor, EquipmentCategory.ARMOR, 41000, 1, ItemUpgradePath.UNIQUE, "Dark Armor");
        put(armor, EquipmentCategory.ARMOR, 42000, 1, ItemUpgradePath.UNIQUE, "Dark Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 43000, 1, ItemUpgradePath.UNIQUE, "Dark Leggings");
        put(armor, EquipmentCategory.ARMOR, 50000, 1, ItemUpgradePath.STANDARD_ARMOR, "Brigand Hood");
        put(armor, EquipmentCategory.ARMOR, 51000, 1, ItemUpgradePath.STANDARD_ARMOR, "Brigand Armor");
        put(armor, EquipmentCategory.ARMOR, 52000, 1, ItemUpgradePath.STANDARD_ARMOR, "Brigand Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 53000, 1, ItemUpgradePath.STANDARD_ARMOR, "Brigand Trousers");
        put(armor, EquipmentCategory.ARMOR, 60000, 1, ItemUpgradePath.UNIQUE, "Shadow Mask");
        put(armor, EquipmentCategory.ARMOR, 61000, 1, ItemUpgradePath.UNIQUE, "Shadow Garb");
        put(armor, EquipmentCategory.ARMOR, 62000, 1, ItemUpgradePath.UNIQUE, "Shadow Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 63000, 1, ItemUpgradePath.UNIQUE, "Shadow Leggings");
        put(armor, EquipmentCategory.ARMOR, 70000, 1, ItemUpgradePath.UNIQUE, "Black Iron Helm");
        put(armor, EquipmentCategory.ARMOR, 71000, 1, ItemUpgradePath.UNIQUE, "Black Iron Armor");
        put(armor, EquipmentCategory.ARMOR, 72000, 1, ItemUpgradePath.UNIQUE, "Black Iron Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 73000, 1, ItemUpgradePath.UNIQUE, "Black Iron Leggings");
        put(armor, EquipmentCategory.ARMOR, 80000, 1, ItemUpgradePath.NONE, "Smough's Helm");
        put(armor, EquipmentCategory.ARMOR, 81000, 1, ItemUpgradePath.NONE, "Smough's Armor");
        put(armor, EquipmentCategory.ARMOR, 82000, 1, ItemUpgradePath.NONE, "Smough's Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 83000, 1, ItemUpgradePath.NONE, "Smough's Leggings");
        put(armor, EquipmentCategory.ARMOR, 90000, 1, ItemUpgradePath.NONE, "Six-Eyed Helm of the Channelers");
        put(armor, EquipmentCategory.ARMOR, 91000, 1, ItemUpgradePath.NONE, "Robe of the Channelers");
        put(armor, EquipmentCategory.ARMOR, 92000, 1, ItemUpgradePath.NONE, "Gauntlets of the Channelers");
        put(armor, EquipmentCategory.ARMOR, 93000, 1, ItemUpgradePath.NONE, "Waistcloth of the Channelers");
        put(armor, EquipmentCategory.ARMOR, 100000, 1, ItemUpgradePath.UNIQUE, "Helm of Favor");
        put(armor, EquipmentCategory.ARMOR, 101000, 1, ItemUpgradePath.UNIQUE, "Embraced Armor of Favor");
        put(armor, EquipmentCategory.ARMOR, 102000, 1, ItemUpgradePath.UNIQUE, "Gauntlets of Favor");
        put(armor, EquipmentCategory.ARMOR, 103000, 1, ItemUpgradePath.UNIQUE, "Leggings of Favor");
        put(armor, EquipmentCategory.ARMOR, 110000, 1, ItemUpgradePath.NONE, "Helm of the Wise");
        put(armor, EquipmentCategory.ARMOR, 111000, 1, ItemUpgradePath.NONE, "Armor of the Glorious");
        put(armor, EquipmentCategory.ARMOR, 112000, 1, ItemUpgradePath.NONE, "Gauntlets of the Vanquisher");
        put(armor, EquipmentCategory.ARMOR, 113000, 1, ItemUpgradePath.NONE, "Boots of the Explorer");
        put(armor, EquipmentCategory.ARMOR, 120000, 1, ItemUpgradePath.NONE, "Stone Helm");
        put(armor, EquipmentCategory.ARMOR, 121000, 1, ItemUpgradePath.NONE, "Stone Armor");
        put(armor, EquipmentCategory.ARMOR, 122000, 1, ItemUpgradePath.NONE, "Stone Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 123000, 1, ItemUpgradePath.NONE, "Stone Leggings");
        put(armor, EquipmentCategory.ARMOR, 130000, 1, ItemUpgradePath.NONE, "Crystalline Helm");
        put(armor, EquipmentCategory.ARMOR, 131000, 1, ItemUpgradePath.NONE, "Crystalline Armor");
        put(armor, EquipmentCategory.ARMOR, 132000, 1, ItemUpgradePath.NONE, "Crystalline Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 133000, 1, ItemUpgradePath.NONE, "Crystalline Leggings");
        put(armor, EquipmentCategory.ARMOR, 140000, 1, ItemUpgradePath.UNIQUE, "Mask of the Sealer");
        put(armor, EquipmentCategory.ARMOR, 141000, 1, ItemUpgradePath.UNIQUE, "Crimson Robe");
        put(armor, EquipmentCategory.ARMOR, 142000, 1, ItemUpgradePath.UNIQUE, "Crimson Gloves");
        put(armor, EquipmentCategory.ARMOR, 143000, 1, ItemUpgradePath.UNIQUE, "Crimson Waistcloth");
        put(armor, EquipmentCategory.ARMOR, 150000, 1, ItemUpgradePath.UNIQUE, "Mask of Velka");
        put(armor, EquipmentCategory.ARMOR, 151000, 1, ItemUpgradePath.UNIQUE, "Black Cleric Robe");
        put(armor, EquipmentCategory.ARMOR, 152000, 1, ItemUpgradePath.UNIQUE, "Black Manchette");
        put(armor, EquipmentCategory.ARMOR, 153000, 1, ItemUpgradePath.UNIQUE, "Black Tights");
        put(armor, EquipmentCategory.ARMOR, 160000, 1, ItemUpgradePath.STANDARD_ARMOR, "Iron Helm");
        put(armor, EquipmentCategory.ARMOR, 161000, 1, ItemUpgradePath.STANDARD_ARMOR, "Armor of the Sun");
        put(armor, EquipmentCategory.ARMOR, 162000, 1, ItemUpgradePath.STANDARD_ARMOR, "Iron Bracelet");
        put(armor, EquipmentCategory.ARMOR, 163000, 1, ItemUpgradePath.STANDARD_ARMOR, "Iron Leggings");
        put(armor, EquipmentCategory.ARMOR, 170000, 1, ItemUpgradePath.STANDARD_ARMOR, "Chain Helm");
        put(armor, EquipmentCategory.ARMOR, 171000, 1, ItemUpgradePath.STANDARD_ARMOR, "Chain Armor");
        put(armor, EquipmentCategory.ARMOR, 172000, 1, ItemUpgradePath.STANDARD_ARMOR, "Leather Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 173000, 1, ItemUpgradePath.STANDARD_ARMOR, "Chain Leggings");
        put(armor, EquipmentCategory.ARMOR, 180000, 1, ItemUpgradePath.STANDARD_ARMOR, "Cleric Helm");
        put(armor, EquipmentCategory.ARMOR, 181000, 1, ItemUpgradePath.STANDARD_ARMOR, "Cleric Armor");
        put(armor, EquipmentCategory.ARMOR, 182000, 1, ItemUpgradePath.STANDARD_ARMOR, "Cleric Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 183000, 1, ItemUpgradePath.STANDARD_ARMOR, "Cleric Leggings");
        put(armor, EquipmentCategory.ARMOR, 190000, 1, ItemUpgradePath.NONE, "Sunlight Maggot");
        put(armor, EquipmentCategory.ARMOR, 200000, 1, ItemUpgradePath.UNIQUE, "Helm of Thorns");
        put(armor, EquipmentCategory.ARMOR, 201000, 1, ItemUpgradePath.UNIQUE, "Armor of Thorns");
        put(armor, EquipmentCategory.ARMOR, 202000, 1, ItemUpgradePath.UNIQUE, "Gauntlets of Thorns");
        put(armor, EquipmentCategory.ARMOR, 203000, 1, ItemUpgradePath.UNIQUE, "Leggings of Thorns");
        put(armor, EquipmentCategory.ARMOR, 210000, 1, ItemUpgradePath.STANDARD_ARMOR, "Standard Helm");
        put(armor, EquipmentCategory.ARMOR, 211000, 1, ItemUpgradePath.STANDARD_ARMOR, "Hard Leather Armor");
        put(armor, EquipmentCategory.ARMOR, 212000, 1, ItemUpgradePath.STANDARD_ARMOR, "Hard Leather Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 213000, 1, ItemUpgradePath.STANDARD_ARMOR, "Hard Leather Boots");
        put(armor, EquipmentCategory.ARMOR, 220000, 1, ItemUpgradePath.STANDARD_ARMOR, "Sorcerer Hat");
        put(armor, EquipmentCategory.ARMOR, 221000, 1, ItemUpgradePath.STANDARD_ARMOR, "Sorcerer Cloak");
        put(armor, EquipmentCategory.ARMOR, 222000, 1, ItemUpgradePath.STANDARD_ARMOR, "Sorcerer Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 223000, 1, ItemUpgradePath.STANDARD_ARMOR, "Sorcerer Boots");
        put(armor, EquipmentCategory.ARMOR, 230000, 1, ItemUpgradePath.STANDARD_ARMOR, "Tattered Cloth Hood");
        put(armor, EquipmentCategory.ARMOR, 231000, 1, ItemUpgradePath.STANDARD_ARMOR, "Tattered Cloth Robe");
        put(armor, EquipmentCategory.ARMOR, 232000, 1, ItemUpgradePath.STANDARD_ARMOR, "Tattered Cloth Manchette");
        put(armor, EquipmentCategory.ARMOR, 233000, 1, ItemUpgradePath.STANDARD_ARMOR, "Heavy Boots");
        put(armor, EquipmentCategory.ARMOR, 240000, 1, ItemUpgradePath.STANDARD_ARMOR, "Pharis's Hat");
        put(armor, EquipmentCategory.ARMOR, 241000, 1, ItemUpgradePath.STANDARD_ARMOR, "Leather Armor");
        put(armor, EquipmentCategory.ARMOR, 242000, 1, ItemUpgradePath.STANDARD_ARMOR, "Leather Gloves");
        put(armor, EquipmentCategory.ARMOR, 243000, 1, ItemUpgradePath.STANDARD_ARMOR, "Leather Boots");
        put(armor, EquipmentCategory.ARMOR, 250000, 1, ItemUpgradePath.UNIQUE, "Painting Guardian Hood");
        put(armor, EquipmentCategory.ARMOR, 251000, 1, ItemUpgradePath.UNIQUE, "Painting Guardian Robe");
        put(armor, EquipmentCategory.ARMOR, 252000, 1, ItemUpgradePath.UNIQUE, "Painting Guardian Gloves");
        put(armor, EquipmentCategory.ARMOR, 253000, 1, ItemUpgradePath.UNIQUE, "Painting Guardian Waistcloth");
        put(armor, EquipmentCategory.ARMOR, 270000, 1, ItemUpgradePath.NONE, "Ornstein's Helm");
        put(armor, EquipmentCategory.ARMOR, 271000, 1, ItemUpgradePath.NONE, "Ornstein's Armor");
        put(armor, EquipmentCategory.ARMOR, 272000, 1, ItemUpgradePath.NONE, "Ornstein's Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 273000, 1, ItemUpgradePath.NONE, "Ornstein's Leggings");
        put(armor, EquipmentCategory.ARMOR, 280000, 1, ItemUpgradePath.UNIQUE, "Eastern Helm");
        put(armor, EquipmentCategory.ARMOR, 281000, 1, ItemUpgradePath.UNIQUE, "Eastern Armor");
        put(armor, EquipmentCategory.ARMOR, 282000, 1, ItemUpgradePath.UNIQUE, "Eastern Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 283000, 1, ItemUpgradePath.UNIQUE, "Eastern Leggings");
        put(armor, EquipmentCategory.ARMOR, 290000, 1, ItemUpgradePath.UNIQUE, "Xanthous Crown");
        put(armor, EquipmentCategory.ARMOR, 291000, 1, ItemUpgradePath.UNIQUE, "Xanthous Overcoat");
        put(armor, EquipmentCategory.ARMOR, 292000, 1, ItemUpgradePath.UNIQUE, "Xanthous Gloves");
        put(armor, EquipmentCategory.ARMOR, 293000, 1, ItemUpgradePath.UNIQUE, "Xanthous Waistcloth");
        put(armor, EquipmentCategory.ARMOR, 300000, 1, ItemUpgradePath.STANDARD_ARMOR, "Thief Mask");
        put(armor, EquipmentCategory.ARMOR, 301000, 1, ItemUpgradePath.STANDARD_ARMOR, "Black Leather Armor");
        put(armor, EquipmentCategory.ARMOR, 302000, 1, ItemUpgradePath.STANDARD_ARMOR, "Black Leather Gloves");
        put(armor, EquipmentCategory.ARMOR, 303000, 1, ItemUpgradePath.STANDARD_ARMOR, "Black Leather Boots");
        put(armor, EquipmentCategory.ARMOR, 310000, 1, ItemUpgradePath.STANDARD_ARMOR, "Priest's Hat");
        put(armor, EquipmentCategory.ARMOR, 311000, 1, ItemUpgradePath.STANDARD_ARMOR, "Holy Robe");
        put(armor, EquipmentCategory.ARMOR, 312000, 1, ItemUpgradePath.STANDARD_ARMOR, "Traveling Gloves (Holy)");
        put(armor, EquipmentCategory.ARMOR, 313000, 1, ItemUpgradePath.STANDARD_ARMOR, "Holy Trousers");
        put(armor, EquipmentCategory.ARMOR, 320000, 1, ItemUpgradePath.UNIQUE, "Black Knight Helm");
        put(armor, EquipmentCategory.ARMOR, 321000, 1, ItemUpgradePath.UNIQUE, "Black Knight Armor");
        put(armor, EquipmentCategory.ARMOR, 322000, 1, ItemUpgradePath.UNIQUE, "Black Knight Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 323000, 1, ItemUpgradePath.UNIQUE, "Black Knight Leggings");
        put(armor, EquipmentCategory.ARMOR, 330000, 1, ItemUpgradePath.NONE, "Crown of Dusk");
        put(armor, EquipmentCategory.ARMOR, 331000, 1, ItemUpgradePath.UNIQUE, "Antiquated Dress");
        put(armor, EquipmentCategory.ARMOR, 332000, 1, ItemUpgradePath.UNIQUE, "Antiquated Gloves");
        put(armor, EquipmentCategory.ARMOR, 333000, 1, ItemUpgradePath.UNIQUE, "Antiquated Skirt");
        put(armor, EquipmentCategory.ARMOR, 340000, 1, ItemUpgradePath.UNIQUE, "Witch Hat");
        put(armor, EquipmentCategory.ARMOR, 341000, 1, ItemUpgradePath.UNIQUE, "Witch Cloak");
        put(armor, EquipmentCategory.ARMOR, 342000, 1, ItemUpgradePath.UNIQUE, "Witch Gloves");
        put(armor, EquipmentCategory.ARMOR, 343000, 1, ItemUpgradePath.UNIQUE, "Witch Skirt");
        put(armor, EquipmentCategory.ARMOR, 350000, 1, ItemUpgradePath.STANDARD_ARMOR, "Elite Knight Helm");
        put(armor, EquipmentCategory.ARMOR, 351000, 1, ItemUpgradePath.STANDARD_ARMOR, "Elite Knight Armor");
        put(armor, EquipmentCategory.ARMOR, 352000, 1, ItemUpgradePath.STANDARD_ARMOR, "Elite Knight Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 353000, 1, ItemUpgradePath.STANDARD_ARMOR, "Elite Knight Leggings");
        put(armor, EquipmentCategory.ARMOR, 360000, 1, ItemUpgradePath.STANDARD_ARMOR, "Wanderer Hood");
        put(armor, EquipmentCategory.ARMOR, 361000, 1, ItemUpgradePath.STANDARD_ARMOR, "Wanderer Coat");
        put(armor, EquipmentCategory.ARMOR, 362000, 1, ItemUpgradePath.STANDARD_ARMOR, "Wanderer Manchette");
        put(armor, EquipmentCategory.ARMOR, 363000, 1, ItemUpgradePath.STANDARD_ARMOR, "Wanderer Boots");
        put(armor, EquipmentCategory.ARMOR, 380000, 1, ItemUpgradePath.UNIQUE, "Big Hat");
        put(armor, EquipmentCategory.ARMOR, 381000, 1, ItemUpgradePath.UNIQUE, "Sage Robe");
        put(armor, EquipmentCategory.ARMOR, 382000, 1, ItemUpgradePath.STANDARD_ARMOR, "Traveling Gloves (Sage)");
        put(armor, EquipmentCategory.ARMOR, 383000, 1, ItemUpgradePath.STANDARD_ARMOR, "Traveling Boots");
        put(armor, EquipmentCategory.ARMOR, 390000, 1, ItemUpgradePath.STANDARD_ARMOR, "Knight Helm");
        put(armor, EquipmentCategory.ARMOR, 391000, 1, ItemUpgradePath.STANDARD_ARMOR, "Knight Armor");
        put(armor, EquipmentCategory.ARMOR, 392000, 1, ItemUpgradePath.STANDARD_ARMOR, "Knight Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 393000, 1, ItemUpgradePath.STANDARD_ARMOR, "Knight Leggings");
        put(armor, EquipmentCategory.ARMOR, 400000, 1, ItemUpgradePath.STANDARD_ARMOR, "Dingy Hood");
        put(armor, EquipmentCategory.ARMOR, 401000, 1, ItemUpgradePath.STANDARD_ARMOR, "Dingy Robe");
        put(armor, EquipmentCategory.ARMOR, 402000, 1, ItemUpgradePath.STANDARD_ARMOR, "Dingy Gloves");
        put(armor, EquipmentCategory.ARMOR, 403000, 1, ItemUpgradePath.STANDARD_ARMOR, "Blood-Stained Skirt");
        put(armor, EquipmentCategory.ARMOR, 410000, 1, ItemUpgradePath.STANDARD_ARMOR, "Maiden Hood");
        put(armor, EquipmentCategory.ARMOR, 411000, 1, ItemUpgradePath.STANDARD_ARMOR, "Maiden Robe");
        put(armor, EquipmentCategory.ARMOR, 412000, 1, ItemUpgradePath.STANDARD_ARMOR, "Maiden Gloves");
        put(armor, EquipmentCategory.ARMOR, 413000, 1, ItemUpgradePath.STANDARD_ARMOR, "Maiden Skirt");
        put(armor, EquipmentCategory.ARMOR, 420000, 1, ItemUpgradePath.UNIQUE, "Silver Knight Helm");
        put(armor, EquipmentCategory.ARMOR, 421000, 1, ItemUpgradePath.UNIQUE, "Silver Knight Armor");
        put(armor, EquipmentCategory.ARMOR, 422000, 1, ItemUpgradePath.UNIQUE, "Silver Knight Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 423000, 1, ItemUpgradePath.UNIQUE, "Silver Knight Leggings");
        put(armor, EquipmentCategory.ARMOR, 440000, 1, ItemUpgradePath.NONE, "Havel's Helm");
        put(armor, EquipmentCategory.ARMOR, 441000, 1, ItemUpgradePath.NONE, "Havel's Armor");
        put(armor, EquipmentCategory.ARMOR, 442000, 1, ItemUpgradePath.NONE, "Havel's Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 443000, 1, ItemUpgradePath.NONE, "Havel's Leggings");
        put(armor, EquipmentCategory.ARMOR, 450000, 1, ItemUpgradePath.UNIQUE, "Brass Helm");
        put(armor, EquipmentCategory.ARMOR, 451000, 1, ItemUpgradePath.UNIQUE, "Brass Armor");
        put(armor, EquipmentCategory.ARMOR, 452000, 1, ItemUpgradePath.UNIQUE, "Brass Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 453000, 1, ItemUpgradePath.UNIQUE, "Brass Leggings");
        put(armor, EquipmentCategory.ARMOR, 460000, 1, ItemUpgradePath.NONE, "Gold-Hemmed Black Hood");
        put(armor, EquipmentCategory.ARMOR, 461000, 1, ItemUpgradePath.NONE, "Gold-Hemmed Black Cloak");
        put(armor, EquipmentCategory.ARMOR, 462000, 1, ItemUpgradePath.NONE, "Gold-Hemmed Black Gloves");
        put(armor, EquipmentCategory.ARMOR, 463000, 1, ItemUpgradePath.NONE, "Gold-Hemmed Black Skirt");
        put(armor, EquipmentCategory.ARMOR, 470000, 1, ItemUpgradePath.NONE, "Golem Helm");
        put(armor, EquipmentCategory.ARMOR, 471000, 1, ItemUpgradePath.NONE, "Golem Armor");
        put(armor, EquipmentCategory.ARMOR, 472000, 1, ItemUpgradePath.NONE, "Golem Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 473000, 1, ItemUpgradePath.NONE, "Golem Leggings");
        put(armor, EquipmentCategory.ARMOR, 480000, 1, ItemUpgradePath.STANDARD_ARMOR, "Hollow Soldier Helm");
        put(armor, EquipmentCategory.ARMOR, 481000, 1, ItemUpgradePath.STANDARD_ARMOR, "Hollow Soldier Armor");
        put(armor, EquipmentCategory.ARMOR, 483000, 1, ItemUpgradePath.STANDARD_ARMOR, "Hollow Soldier Waistcloth");
        put(armor, EquipmentCategory.ARMOR, 490000, 1, ItemUpgradePath.STANDARD_ARMOR, "Steel Helm");
        put(armor, EquipmentCategory.ARMOR, 491000, 1, ItemUpgradePath.STANDARD_ARMOR, "Steel Armor");
        put(armor, EquipmentCategory.ARMOR, 492000, 1, ItemUpgradePath.STANDARD_ARMOR, "Steel Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 493000, 1, ItemUpgradePath.STANDARD_ARMOR, "Steel Leggings");
        put(armor, EquipmentCategory.ARMOR, 500000, 1, ItemUpgradePath.STANDARD_ARMOR, "Hollow Thief's Hood");
        put(armor, EquipmentCategory.ARMOR, 501000, 1, ItemUpgradePath.STANDARD_ARMOR, "Hollow Thief's Leather Armor");
        put(armor, EquipmentCategory.ARMOR, 503000, 1, ItemUpgradePath.STANDARD_ARMOR, "Hollow Thief's Tights");
        put(armor, EquipmentCategory.ARMOR, 510000, 1, ItemUpgradePath.STANDARD_ARMOR, "Balder Helm");
        put(armor, EquipmentCategory.ARMOR, 511000, 1, ItemUpgradePath.STANDARD_ARMOR, "Balder Armor");
        put(armor, EquipmentCategory.ARMOR, 512000, 1, ItemUpgradePath.STANDARD_ARMOR, "Balder Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 513000, 1, ItemUpgradePath.STANDARD_ARMOR, "Balder Leggings");
        put(armor, EquipmentCategory.ARMOR, 520000, 1, ItemUpgradePath.STANDARD_ARMOR, "Hollow Warrior Helm");
        put(armor, EquipmentCategory.ARMOR, 521000, 1, ItemUpgradePath.STANDARD_ARMOR, "Hollow Warrior Armor");
        put(armor, EquipmentCategory.ARMOR, 523000, 1, ItemUpgradePath.STANDARD_ARMOR, "Hollow Warrior Waistcloth");
        put(armor, EquipmentCategory.ARMOR, 530000, 1, ItemUpgradePath.UNIQUE, "Giant Helm");
        put(armor, EquipmentCategory.ARMOR, 531000, 1, ItemUpgradePath.UNIQUE, "Giant Armor");
        put(armor, EquipmentCategory.ARMOR, 532000, 1, ItemUpgradePath.UNIQUE, "Giant Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 533000, 1, ItemUpgradePath.UNIQUE, "Giant Leggings");
        put(armor, EquipmentCategory.ARMOR, 540000, 1, ItemUpgradePath.NONE, "Crown of the Dark Sun");
        put(armor, EquipmentCategory.ARMOR, 541000, 1, ItemUpgradePath.NONE, "Moonlight Robe");
        put(armor, EquipmentCategory.ARMOR, 542000, 1, ItemUpgradePath.NONE, "Moonlight Gloves");
        put(armor, EquipmentCategory.ARMOR, 543000, 1, ItemUpgradePath.NONE, "Moonlight Waistcloth");
        put(armor, EquipmentCategory.ARMOR, 550000, 1, ItemUpgradePath.NONE, "Crown of the Great Lord");
        put(armor, EquipmentCategory.ARMOR, 551000, 1, ItemUpgradePath.NONE, "Robe of the Great Lord");
        put(armor, EquipmentCategory.ARMOR, 552000, 1, ItemUpgradePath.NONE, "Bracelet of the Great Lord");
        put(armor, EquipmentCategory.ARMOR, 553000, 1, ItemUpgradePath.NONE, "Anklet of the Great Lord");
        put(armor, EquipmentCategory.ARMOR, 560000, 1, ItemUpgradePath.STANDARD_ARMOR, "Sack");
        put(armor, EquipmentCategory.ARMOR, 570000, 1, ItemUpgradePath.NONE, "Symbol of Avarice");
        put(armor, EquipmentCategory.ARMOR, 580000, 1, ItemUpgradePath.STANDARD_ARMOR, "Royal Helm");
        put(armor, EquipmentCategory.ARMOR, 590000, 1, ItemUpgradePath.NONE, "Mask of the Father");
        put(armor, EquipmentCategory.ARMOR, 600000, 1, ItemUpgradePath.NONE, "Mask of the Mother");
        put(armor, EquipmentCategory.ARMOR, 610000, 1, ItemUpgradePath.NONE, "Mask of the Child");
        put(armor, EquipmentCategory.ARMOR, 620000, 1, ItemUpgradePath.UNIQUE, "Fang Boar Helm");
        put(armor, EquipmentCategory.ARMOR, 630000, 1, ItemUpgradePath.UNIQUE, "Gargoyle Helm");
        put(armor, EquipmentCategory.ARMOR, 640000, 1, ItemUpgradePath.STANDARD_ARMOR, "Black Sorcerer Hat");
        put(armor, EquipmentCategory.ARMOR, 641000, 1, ItemUpgradePath.STANDARD_ARMOR, "Black Sorcerer Cloak");
        put(armor, EquipmentCategory.ARMOR, 642000, 1, ItemUpgradePath.STANDARD_ARMOR, "Black Sorcerer Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 643000, 1, ItemUpgradePath.STANDARD_ARMOR, "Black Sorcerer Boots");
        put(armor, EquipmentCategory.ARMOR, 660000, 1, ItemUpgradePath.UNIQUE, "Helm of Artorias");
        put(armor, EquipmentCategory.ARMOR, 661000, 1, ItemUpgradePath.UNIQUE, "Armor of Artorias");
        put(armor, EquipmentCategory.ARMOR, 662000, 1, ItemUpgradePath.UNIQUE, "Gauntlets of Artorias");
        put(armor, EquipmentCategory.ARMOR, 663000, 1, ItemUpgradePath.UNIQUE, "Leggings of Artorias");
        put(armor, EquipmentCategory.ARMOR, 670000, 1, ItemUpgradePath.UNIQUE, "Porcelain Mask");
        put(armor, EquipmentCategory.ARMOR, 671000, 1, ItemUpgradePath.UNIQUE, "Lord's Blade Robe");
        put(armor, EquipmentCategory.ARMOR, 672000, 1, ItemUpgradePath.UNIQUE, "Lord's Blade Gloves");
        put(armor, EquipmentCategory.ARMOR, 673000, 1, ItemUpgradePath.UNIQUE, "Lord's Blade Waistcloth");
        put(armor, EquipmentCategory.ARMOR, 680000, 1, ItemUpgradePath.UNIQUE, "Gough's Helm");
        put(armor, EquipmentCategory.ARMOR, 681000, 1, ItemUpgradePath.UNIQUE, "Gough's Armor");
        put(armor, EquipmentCategory.ARMOR, 682000, 1, ItemUpgradePath.UNIQUE, "Gough's Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 683000, 1, ItemUpgradePath.UNIQUE, "Gough's Leggings");
        put(armor, EquipmentCategory.ARMOR, 690000, 1, ItemUpgradePath.NONE, "Guardian Helm");
        put(armor, EquipmentCategory.ARMOR, 691000, 1, ItemUpgradePath.NONE, "Guardian Armor");
        put(armor, EquipmentCategory.ARMOR, 692000, 1, ItemUpgradePath.NONE, "Guardian Gauntlets");
        put(armor, EquipmentCategory.ARMOR, 693000, 1, ItemUpgradePath.NONE, "Guardian Leggings");
        put(armor, EquipmentCategory.ARMOR, 700000, 1, ItemUpgradePath.UNIQUE, "Snickering Top Hat");
        put(armor, EquipmentCategory.ARMOR, 701000, 1, ItemUpgradePath.UNIQUE, "Chester's Long Coat");
        put(armor, EquipmentCategory.ARMOR, 702000, 1, ItemUpgradePath.UNIQUE, "Chester's Gloves");
        put(armor, EquipmentCategory.ARMOR, 703000, 1, ItemUpgradePath.UNIQUE, "Chester's Trousers");
        put(armor, EquipmentCategory.ARMOR, 710000, 1, ItemUpgradePath.NONE, "Bloated Head");
        put(armor, EquipmentCategory.ARMOR, 720000, 1, ItemUpgradePath.NONE, "Bloated Sorcerer Head");

        put(melee, EquipmentCategory.MELEE_WEAPON, 100000, 1, ItemUpgradePath.INFUSABLE, "Dagger");
        put(melee, EquipmentCategory.MELEE_WEAPON, BASE_ITEM_ID_MELEE_PARRYING_DAGGER, 1, ItemUpgradePath.INFUSABLE, "Parrying Dagger");
        put(melee, EquipmentCategory.MELEE_WEAPON, 102000, 1, ItemUpgradePath.UNIQUE, "Ghost Blade");
        put(melee, EquipmentCategory.MELEE_WEAPON, 103000, 1, ItemUpgradePath.INFUSABLE, "Bandit's Knife");
        put(melee, EquipmentCategory.MELEE_WEAPON, 104000, 1, ItemUpgradePath.UNIQUE, "Priscilla's Dagger");
        put(melee, EquipmentCategory.MELEE_WEAPON, 200000, 1, ItemUpgradePath.INFUSABLE, "Shortsword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 201000, 1, ItemUpgradePath.INFUSABLE, "Longsword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 202000, 1, ItemUpgradePath.INFUSABLE, "Broadsword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 203000, 1, ItemUpgradePath.INFUSABLE, "Broken Straight Sword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 204000, 1, ItemUpgradePath.INFUSABLE, "Balder Side Sword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 205000, 1, ItemUpgradePath.NONE, "Crystal Straight Sword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 206000, 1, ItemUpgradePath.INFUSABLE, "Sunlight Straight Sword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 207000, 1, ItemUpgradePath.INFUSABLE, "Barbed Straight Sword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 208000, 1, ItemUpgradePath.UNIQUE, "Silver Knight Straight Sword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 209000, 1, ItemUpgradePath.UNIQUE, "Astora's Straight Sword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 210000, 1, ItemUpgradePath.INFUSABLE, "Darksword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 211000, 1, ItemUpgradePath.UNIQUE, "Drake Sword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 212000, 1, ItemUpgradePath.INFUSABLE, "Straight Sword Hilt");
        put(melee, EquipmentCategory.MELEE_WEAPON, 300000, 1, ItemUpgradePath.INFUSABLE, "Bastard Sword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 301000, 1, ItemUpgradePath.INFUSABLE, "Claymore");
        put(melee, EquipmentCategory.MELEE_WEAPON, 302000, 1, ItemUpgradePath.INFUSABLE, "Man-serpent Greatsword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 303000, 1, ItemUpgradePath.INFUSABLE, "Flamberge");
        put(melee, EquipmentCategory.MELEE_WEAPON, 304000, 1, ItemUpgradePath.NONE, "Crystal Greatsword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 306000, 1, ItemUpgradePath.UNIQUE, "Stone Greatsword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 307000, 1, ItemUpgradePath.UNIQUE, "Greatsword of Artorias");
        put(melee, EquipmentCategory.MELEE_WEAPON, 309000, 1, ItemUpgradePath.UNIQUE, "Moonlight Greatsword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 310000, 1, ItemUpgradePath.UNIQUE, "Black Knight Sword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 311000, 1, ItemUpgradePath.UNIQUE, "Greatsword of Artorias (Cursed)");
        put(melee, EquipmentCategory.MELEE_WEAPON, 314000, 1, ItemUpgradePath.UNIQUE, "Great Lord Greatsword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 350000, 1, ItemUpgradePath.INFUSABLE, "Zweihander");
        put(melee, EquipmentCategory.MELEE_WEAPON, 351000, 1, ItemUpgradePath.INFUSABLE, "Greatsword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 352000, 1, ItemUpgradePath.INFUSABLE, "Demon Great Machete");
        put(melee, EquipmentCategory.MELEE_WEAPON, 354000, 1, ItemUpgradePath.UNIQUE, "Dragon Greatsword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 355000, 1, ItemUpgradePath.UNIQUE, "Black Knight Greatsword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 400000, 1, ItemUpgradePath.INFUSABLE, "Scimitar");
        put(melee, EquipmentCategory.MELEE_WEAPON, 401000, 1, ItemUpgradePath.INFUSABLE, "Falchion");
        put(melee, EquipmentCategory.MELEE_WEAPON, 402000, 1, ItemUpgradePath.INFUSABLE, "Shotel");
        put(melee, EquipmentCategory.MELEE_WEAPON, 403000, 1, ItemUpgradePath.UNIQUE, "Jagged Ghost Blade");
        put(melee, EquipmentCategory.MELEE_WEAPON, 405000, 1, ItemUpgradePath.INFUSABLE, "Painting Guardian Sword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 406000, 1, ItemUpgradePath.UNIQUE, "Quelaag's Furysword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 450000, 1, ItemUpgradePath.INFUSABLE, "Server");
        put(melee, EquipmentCategory.MELEE_WEAPON, 451000, 1, ItemUpgradePath.INFUSABLE, "Murakumo");
        put(melee, EquipmentCategory.MELEE_WEAPON, 453000, 1, ItemUpgradePath.UNIQUE, "Gravelord Sword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 500000, 1, ItemUpgradePath.INFUSABLE, "Uchigatana");
        put(melee, EquipmentCategory.MELEE_WEAPON, 501000, 1, ItemUpgradePath.INFUSABLE, "Washing Pole");
        put(melee, EquipmentCategory.MELEE_WEAPON, 502000, 1, ItemUpgradePath.INFUSABLE, "Iaito");
        put(melee, EquipmentCategory.MELEE_WEAPON, 503000, 1, ItemUpgradePath.UNIQUE, "Chaos Blade");
        put(melee, EquipmentCategory.MELEE_WEAPON, 600000, 1, ItemUpgradePath.INFUSABLE, "Mail Breaker");
        put(melee, EquipmentCategory.MELEE_WEAPON, 601000, 1, ItemUpgradePath.INFUSABLE, "Rapier");
        put(melee, EquipmentCategory.MELEE_WEAPON, 602000, 1, ItemUpgradePath.INFUSABLE, "Estoc");
        put(melee, EquipmentCategory.MELEE_WEAPON, 603000, 1, ItemUpgradePath.UNIQUE, "Velka's Rapier");
        put(melee, EquipmentCategory.MELEE_WEAPON, 604000, 1, ItemUpgradePath.INFUSABLE, "Ricard's Rapier");
        put(melee, EquipmentCategory.MELEE_WEAPON, 700000, 1, ItemUpgradePath.INFUSABLE, "Hand Axe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 701000, 1, ItemUpgradePath.INFUSABLE, "Battle Axe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 702000, 1, ItemUpgradePath.UNIQUE, "Crescent Axe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 703000, 1, ItemUpgradePath.INFUSABLE, "Butcher Knife");
        put(melee, EquipmentCategory.MELEE_WEAPON, 704000, 1, ItemUpgradePath.UNIQUE, "Golem Axe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 705000, 1, ItemUpgradePath.INFUSABLE, "Gargoyle Tail Axe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 750000, 1, ItemUpgradePath.INFUSABLE, "Greataxe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 751000, 1, ItemUpgradePath.INFUSABLE, "Demon's Greataxe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 752000, 1, ItemUpgradePath.UNIQUE, "Dragon King Greataxe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 753000, 1, ItemUpgradePath.UNIQUE, "Black Knight Greataxe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 800000, 1, ItemUpgradePath.INFUSABLE, "Club");
        put(melee, EquipmentCategory.MELEE_WEAPON, 801000, 1, ItemUpgradePath.INFUSABLE, "Mace");
        put(melee, EquipmentCategory.MELEE_WEAPON, 802000, 1, ItemUpgradePath.INFUSABLE, "Morning Star");
        put(melee, EquipmentCategory.MELEE_WEAPON, 803000, 1, ItemUpgradePath.INFUSABLE, "Warpick");
        put(melee, EquipmentCategory.MELEE_WEAPON, 804000, 1, ItemUpgradePath.INFUSABLE, "Pickaxe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 809000, 1, ItemUpgradePath.INFUSABLE, "Reinforced Club");
        put(melee, EquipmentCategory.MELEE_WEAPON, 810000, 1, ItemUpgradePath.INFUSABLE, "Blacksmith Hammer");
        put(melee, EquipmentCategory.MELEE_WEAPON, 811000, 1, ItemUpgradePath.UNIQUE, "Blacksmith Giant Hammer");
        put(melee, EquipmentCategory.MELEE_WEAPON, 812000, 1, ItemUpgradePath.UNIQUE, "Hammer of Vamos");
        put(melee, EquipmentCategory.MELEE_WEAPON, 850000, 1, ItemUpgradePath.INFUSABLE, "Great Club");
        put(melee, EquipmentCategory.MELEE_WEAPON, 851000, 1, ItemUpgradePath.UNIQUE, "Grant");
        put(melee, EquipmentCategory.MELEE_WEAPON, 852000, 1, ItemUpgradePath.INFUSABLE, "Demon's Great Hammer");
        put(melee, EquipmentCategory.MELEE_WEAPON, 854000, 1, ItemUpgradePath.UNIQUE, "Dragon Tooth");
        put(melee, EquipmentCategory.MELEE_WEAPON, 855000, 1, ItemUpgradePath.INFUSABLE, "Large Club");
        put(melee, EquipmentCategory.MELEE_WEAPON, 856000, 1, ItemUpgradePath.UNIQUE, "Smough's Hammer");
        put(melee, EquipmentCategory.MELEE_WEAPON, 901000, 1, ItemUpgradePath.INFUSABLE, "Caestus");
        put(melee, EquipmentCategory.MELEE_WEAPON, 902000, 1, ItemUpgradePath.INFUSABLE, "Claw");
        put(melee, EquipmentCategory.MELEE_WEAPON, 903000, 1, ItemUpgradePath.UNIQUE, "Dragon Bone Fist");
        put(melee, EquipmentCategory.MELEE_WEAPON, BASE_ITEM_ID_MELEE_DARK_HAND, 1, ItemUpgradePath.NONE, "Dark Hand");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1000000, 1, ItemUpgradePath.INFUSABLE, "Spear");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1001000, 1, ItemUpgradePath.INFUSABLE, "Winged Spear");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1002000, 1, ItemUpgradePath.INFUSABLE, "Partizan");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1003000, 1, ItemUpgradePath.UNIQUE, "Demon's Spear");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1004000, 1, ItemUpgradePath.UNIQUE, "Channeler's Trident");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1006000, 1, ItemUpgradePath.UNIQUE, "Silver Knight Spear");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1050000, 1, ItemUpgradePath.INFUSABLE, "Pike");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1051000, 1, ItemUpgradePath.UNIQUE, "Dragonslayer Spear");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1052000, 1, ItemUpgradePath.UNIQUE, "Moonlight Butterfly Horn");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1100000, 1, ItemUpgradePath.INFUSABLE, "Halberd");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1101000, 1, ItemUpgradePath.UNIQUE, "Giant's Halberd");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1102000, 1, ItemUpgradePath.UNIQUE, "Titanite Catch Pole");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1103000, 1, ItemUpgradePath.INFUSABLE, "Gargoyle's Halberd");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1105000, 1, ItemUpgradePath.UNIQUE, "Black Knight Halberd");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1106000, 1, ItemUpgradePath.INFUSABLE, "Lucerne ");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1107000, 1, ItemUpgradePath.INFUSABLE, "Scythe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1150000, 1, ItemUpgradePath.INFUSABLE, "Great Scythe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1151000, 1, ItemUpgradePath.UNIQUE, "Lifehunt Scythe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1600000, 1, ItemUpgradePath.INFUSABLE, "Whip");
        put(melee, EquipmentCategory.MELEE_WEAPON, 1601000, 1, ItemUpgradePath.INFUSABLE, "Notched Whip");
        put(melee, EquipmentCategory.MELEE_WEAPON, 9010000, 1, ItemUpgradePath.UNIQUE, "Gold Tracer");
        put(melee, EquipmentCategory.MELEE_WEAPON, 9011000, 1, ItemUpgradePath.UNIQUE, "Dark Silver Tracer");
        put(melee, EquipmentCategory.MELEE_WEAPON, 9012000, 1, ItemUpgradePath.UNIQUE, "Abyss Greatsword");
        put(melee, EquipmentCategory.MELEE_WEAPON, 9015000, 1, ItemUpgradePath.UNIQUE, "Stone Greataxe");
        put(melee, EquipmentCategory.MELEE_WEAPON, 9016000, 1, ItemUpgradePath.INFUSABLE, "Four-pronged Plow");
        put(melee, EquipmentCategory.MELEE_WEAPON, 9019000, 1, ItemUpgradePath.INFUSABLE, "Guardian Tail");
        put(melee, EquipmentCategory.MELEE_WEAPON, 9020000, 1, ItemUpgradePath.UNIQUE, "Obsidian Greatsword");

        put(ranged, EquipmentCategory.RANGED_WEAPON, 1200000, 1, ItemUpgradePath.INFUSABLE, "Short Bow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 1201000, 1, ItemUpgradePath.INFUSABLE, "Longbow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 1202000, 1, ItemUpgradePath.INFUSABLE, "Black Bow of Pharis");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 1203000, 1, ItemUpgradePath.UNIQUE, "Dragonslayer Greatbow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 1204000, 1, ItemUpgradePath.INFUSABLE, "Composite Bow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 1205000, 1, ItemUpgradePath.UNIQUE, "Darkmoon Bow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 1250000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Light Crossbow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 1251000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Heavy Crossbow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 1252000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Avelyn");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 1253000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Sniper Crossbow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2000000, 999, ItemUpgradePath.NONE, "Standard Arrow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2001000, 999, ItemUpgradePath.NONE, "Large Arrow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2002000, 999, ItemUpgradePath.NONE, "Feather Arrow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2003000, 999, ItemUpgradePath.NONE, "Fire Arrow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2004000, 999, ItemUpgradePath.NONE, "Poison Arrow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2005000, 999, ItemUpgradePath.NONE, "Moonlight Arrow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2006000, 999, ItemUpgradePath.NONE, "Wooden Arrow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2007000, 999, ItemUpgradePath.NONE, "Dragonslayer Arrow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2008000, 999, ItemUpgradePath.NONE, "Gough's Great Arrow");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2100000, 999, ItemUpgradePath.NONE, "Standard Bolt");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2101000, 999, ItemUpgradePath.NONE, "Heavy Bolt");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2102000, 999, ItemUpgradePath.NONE, "Sniper Bolt");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2103000, 999, ItemUpgradePath.NONE, "Wood Bolt");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 2104000, 999, ItemUpgradePath.NONE, "Lightning Bolt");
        put(ranged, EquipmentCategory.RANGED_WEAPON, 9021000, 1, ItemUpgradePath.UNIQUE, "Gough's Greatbow");

        put(shield, EquipmentCategory.SHIELD, BASE_ITEM_ID_SHIELD_SKULL_LANTERN, 1, ItemUpgradePath.NONE, "Skull Lantern");
        put(shield, EquipmentCategory.SHIELD, 1400000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "East-West Shield");
        put(shield, EquipmentCategory.SHIELD, 1401000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Wooden Shield");
        put(shield, EquipmentCategory.SHIELD, 1402000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Large Leather Shield");
        put(shield, EquipmentCategory.SHIELD, 1403000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Small Leather Shield");
        put(shield, EquipmentCategory.SHIELD, 1404000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Target Shield");
        put(shield, EquipmentCategory.SHIELD, 1405000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Buckler");
        put(shield, EquipmentCategory.SHIELD, 1406000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Cracked Round Shield");
        put(shield, EquipmentCategory.SHIELD, 1408000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Leather Shield");
        put(shield, EquipmentCategory.SHIELD, 1409000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Plank Shield");
        put(shield, EquipmentCategory.SHIELD, 1410000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Caduceus Round Shield");
        put(shield, EquipmentCategory.SHIELD, 1411000, 1, ItemUpgradePath.UNIQUE, "Crystal Ring Shield");
        put(shield, EquipmentCategory.SHIELD, 1450000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Heater Shield");
        put(shield, EquipmentCategory.SHIELD, 1451000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Knight Shield");
        put(shield, EquipmentCategory.SHIELD, 1452000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Tower Kite Shield");
        put(shield, EquipmentCategory.SHIELD, 1453000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Grass Crest Shield");
        put(shield, EquipmentCategory.SHIELD, 1454000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Hollow Soldier Shield");
        put(shield, EquipmentCategory.SHIELD, 1455000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Balder Shield");
        put(shield, EquipmentCategory.SHIELD, 1456000, 1, ItemUpgradePath.UNIQUE, "Crest Shield");
        put(shield, EquipmentCategory.SHIELD, 1457000, 1, ItemUpgradePath.UNIQUE, "Dragon Crest Shield");
        put(shield, EquipmentCategory.SHIELD, 1460000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Warrior's Round Shield");
        put(shield, EquipmentCategory.SHIELD, 1461000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Iron Round Shield");
        put(shield, EquipmentCategory.SHIELD, 1462000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Spider Shield");
        put(shield, EquipmentCategory.SHIELD, 1470000, 1, ItemUpgradePath.INFUSABLE, "Spiked Shield");
        put(shield, EquipmentCategory.SHIELD, 1471000, 1, ItemUpgradePath.NONE, "Crystal Shield");
        put(shield, EquipmentCategory.SHIELD, 1472000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Sunlight Shield");
        put(shield, EquipmentCategory.SHIELD, 1473000, 1, ItemUpgradePath.UNIQUE, "Silver Knight Shield");
        put(shield, EquipmentCategory.SHIELD, 1474000, 1, ItemUpgradePath.UNIQUE, "Black Knight Shield");
        put(shield, EquipmentCategory.SHIELD, 1475000, 1, ItemUpgradePath.INFUSABLE, "Pierce Shield");
        put(shield, EquipmentCategory.SHIELD, 1476000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Red and White Round Shield");
        put(shield, EquipmentCategory.SHIELD, 1477000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Caduceus Kite Shield");
        put(shield, EquipmentCategory.SHIELD, 1478000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Gargoyle's Shield");
        put(shield, EquipmentCategory.SHIELD, 1500000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Eagle Shield");
        put(shield, EquipmentCategory.SHIELD, 1501000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Tower Shield");
        put(shield, EquipmentCategory.SHIELD, 1502000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Giant Shield");
        put(shield, EquipmentCategory.SHIELD, 1503000, 1, ItemUpgradePath.UNIQUE, "Stone Greatshield");
        put(shield, EquipmentCategory.SHIELD, 1505000, 1, ItemUpgradePath.UNIQUE, "Havel's Greatshield");
        put(shield, EquipmentCategory.SHIELD, 1506000, 1, ItemUpgradePath.INFUSABLE, "Bonewheel Shield");
        put(shield, EquipmentCategory.SHIELD, 1507000, 1, ItemUpgradePath.UNIQUE, "Greatshield of Artorias");
        put(shield, EquipmentCategory.SHIELD, 9000000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Effigy Shield");
        put(shield, EquipmentCategory.SHIELD, 9001000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Sanctus");
        put(shield, EquipmentCategory.SHIELD, 9002000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Bloodshield");
        put(shield, EquipmentCategory.SHIELD, 9003000, 1, ItemUpgradePath.INFUSABLE_RESTRICTED, "Black Iron Greatshield");
        put(shield, EquipmentCategory.SHIELD, 9014000, 1, ItemUpgradePath.UNIQUE, "Cleansing Greatshield");

        put(spellTools, EquipmentCategory.SPELL_TOOL, 1300000, 1, ItemUpgradePath.NONE, "Sorcerer's Catalyst");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1301000, 1, ItemUpgradePath.NONE, "Beatrice's Catalyst");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1302000, 1, ItemUpgradePath.NONE, "Tin Banishment Catalyst");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1303000, 1, ItemUpgradePath.NONE, "Logan's Catalyst");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1304000, 1, ItemUpgradePath.NONE, "Tin Darkmoon Catalyst");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1305000, 1, ItemUpgradePath.NONE, "Oolacile Ivory Catalyst");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1306000, 1, ItemUpgradePath.NONE, "Tin Crystallization Catalyst");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1307000, 1, ItemUpgradePath.NONE, "Demon's Catalyst");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1308000, 1, ItemUpgradePath.NONE, "Izalith Catalyst");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1330000, 1, ItemUpgradePath.PYRO_FLAME, "Pyromancy Flame");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1332000, 1, ItemUpgradePath.PYRO_ASCENDED, "Pyromancy Flame (Ascended)");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1360000, 1, ItemUpgradePath.NONE, "Talisman");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1361000, 1, ItemUpgradePath.NONE, "Canvas Talisman");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1362000, 1, ItemUpgradePath.NONE, "Thorolund Talisman");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1363000, 1, ItemUpgradePath.NONE, "Ivory Talisman");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1365000, 1, ItemUpgradePath.NONE, "Sunlight Talisman");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1366000, 1, ItemUpgradePath.NONE, "Darkmoon Talisman");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 1367000, 1, ItemUpgradePath.NONE, "Velka's Talisman");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 9017000, 1, ItemUpgradePath.NONE, "Manus Catalyst");
        put(spellTools, EquipmentCategory.SPELL_TOOL, 9018000, 1, ItemUpgradePath.NONE, "Oolacile Catalyst");

        put(spells, EquipmentCategory.SPELL, 3000, 1, ItemUpgradePath.NONE, "Soul Arrow");
        put(spells, EquipmentCategory.SPELL, 3010, 1, ItemUpgradePath.NONE, "Great Soul Arrow");
        put(spells, EquipmentCategory.SPELL, 3020, 1, ItemUpgradePath.NONE, "Heavy Soul Arrow");
        put(spells, EquipmentCategory.SPELL, 3030, 1, ItemUpgradePath.NONE, "Great Heavy Soul Arrow");
        put(spells, EquipmentCategory.SPELL, 3040, 1, ItemUpgradePath.NONE, "Homing Soulmass");
        put(spells, EquipmentCategory.SPELL, 3050, 1, ItemUpgradePath.NONE, "Homing Crystal Soulmass");
        put(spells, EquipmentCategory.SPELL, 3060, 1, ItemUpgradePath.NONE, "Soul Spear");
        put(spells, EquipmentCategory.SPELL, 3070, 1, ItemUpgradePath.NONE, "Crystal Soul Spear");
        put(spells, EquipmentCategory.SPELL, 3100, 1, ItemUpgradePath.NONE, "Magic Weapon");
        put(spells, EquipmentCategory.SPELL, 3110, 1, ItemUpgradePath.NONE, "Great Magic Weapon");
        put(spells, EquipmentCategory.SPELL, 3120, 1, ItemUpgradePath.NONE, "Crystal Magic Weapon");
        put(spells, EquipmentCategory.SPELL, 3300, 1, ItemUpgradePath.NONE, "Magic Shield");
        put(spells, EquipmentCategory.SPELL, 3310, 1, ItemUpgradePath.NONE, "Strong Magic Shield");
        put(spells, EquipmentCategory.SPELL, 3400, 1, ItemUpgradePath.NONE, "Hidden Weapon");
        put(spells, EquipmentCategory.SPELL, 3410, 1, ItemUpgradePath.NONE, "Hidden Body");
        put(spells, EquipmentCategory.SPELL, 3500, 1, ItemUpgradePath.NONE, "Cast Light");
        put(spells, EquipmentCategory.SPELL, 3510, 1, ItemUpgradePath.NONE, "Hush");
        put(spells, EquipmentCategory.SPELL, 3520, 1, ItemUpgradePath.NONE, "Aural Decoy");
        put(spells, EquipmentCategory.SPELL, 3530, 1, ItemUpgradePath.NONE, "Repair");
        put(spells, EquipmentCategory.SPELL, 3540, 1, ItemUpgradePath.NONE, "Fall Control");
        put(spells, EquipmentCategory.SPELL, 3550, 1, ItemUpgradePath.NONE, "Chameleon");
        put(spells, EquipmentCategory.SPELL, 3600, 1, ItemUpgradePath.NONE, "Resist Curse");
        put(spells, EquipmentCategory.SPELL, 3610, 1, ItemUpgradePath.NONE, "Remedy");
        put(spells, EquipmentCategory.SPELL, 3700, 1, ItemUpgradePath.NONE, "White Dragon Breath");
        put(spells, EquipmentCategory.SPELL, 3710, 1, ItemUpgradePath.NONE, "Dark Orb");
        put(spells, EquipmentCategory.SPELL, 3720, 1, ItemUpgradePath.NONE, "Dark Bead");
        put(spells, EquipmentCategory.SPELL, 3730, 1, ItemUpgradePath.NONE, "Dark Fog");
        put(spells, EquipmentCategory.SPELL, 3740, 1, ItemUpgradePath.NONE, "Pursuers");
        put(spells, EquipmentCategory.SPELL, 4000, 1, ItemUpgradePath.NONE, "Fireball");
        put(spells, EquipmentCategory.SPELL, 4010, 1, ItemUpgradePath.NONE, "Fire Orb");
        put(spells, EquipmentCategory.SPELL, 4020, 1, ItemUpgradePath.NONE, "Great Fireball");
        put(spells, EquipmentCategory.SPELL, 4030, 1, ItemUpgradePath.NONE, "Firestorm");
        put(spells, EquipmentCategory.SPELL, 4040, 1, ItemUpgradePath.NONE, "Fire Tempest");
        put(spells, EquipmentCategory.SPELL, 4050, 1, ItemUpgradePath.NONE, "Fire Surge");
        put(spells, EquipmentCategory.SPELL, 4060, 1, ItemUpgradePath.NONE, "Fire Whip");
        put(spells, EquipmentCategory.SPELL, 4100, 1, ItemUpgradePath.NONE, "Combustion");
        put(spells, EquipmentCategory.SPELL, 4110, 1, ItemUpgradePath.NONE, "Great Combustion");
        put(spells, EquipmentCategory.SPELL, 4200, 1, ItemUpgradePath.NONE, "Poison Mist");
        put(spells, EquipmentCategory.SPELL, 4210, 1, ItemUpgradePath.NONE, "Toxic Mist");
        put(spells, EquipmentCategory.SPELL, 4220, 1, ItemUpgradePath.NONE, "Acid Surge");
        put(spells, EquipmentCategory.SPELL, 4300, 1, ItemUpgradePath.NONE, "Iron Flesh");
        put(spells, EquipmentCategory.SPELL, 4310, 1, ItemUpgradePath.NONE, "Flash Sweat");
        put(spells, EquipmentCategory.SPELL, 4360, 1, ItemUpgradePath.NONE, "Undead Rapport");
        put(spells, EquipmentCategory.SPELL, 4400, 1, ItemUpgradePath.NONE, "Power Within");
        put(spells, EquipmentCategory.SPELL, 4500, 1, ItemUpgradePath.NONE, "Great Chaos Fireball");
        put(spells, EquipmentCategory.SPELL, 4510, 1, ItemUpgradePath.NONE, "Chaos Storm");
        put(spells, EquipmentCategory.SPELL, 4520, 1, ItemUpgradePath.NONE, "Chaos Fire Whip");
        put(spells, EquipmentCategory.SPELL, 4530, 1, ItemUpgradePath.NONE, "Black Flame");
        put(spells, EquipmentCategory.SPELL, 5000, 1, ItemUpgradePath.NONE, "Heal");
        put(spells, EquipmentCategory.SPELL, 5010, 1, ItemUpgradePath.NONE, "Great Heal");
        put(spells, EquipmentCategory.SPELL, 5020, 1, ItemUpgradePath.NONE, "Great Heal Except");
        put(spells, EquipmentCategory.SPELL, 5030, 1, ItemUpgradePath.NONE, "Soothing Sunlight");
        put(spells, EquipmentCategory.SPELL, 5040, 1, ItemUpgradePath.NONE, "Replenishment");
        put(spells, EquipmentCategory.SPELL, 5050, 1, ItemUpgradePath.NONE, "Bountiful Sunlight");
        put(spells, EquipmentCategory.SPELL, 5100, 1, ItemUpgradePath.NONE, "Gravelord Sword Dance");
        put(spells, EquipmentCategory.SPELL, 5110, 1, ItemUpgradePath.NONE, "Gravelord Greatsword Dance");
        put(spells, EquipmentCategory.SPELL, 5200, 1, ItemUpgradePath.NONE, "Escape Death");
        put(spells, EquipmentCategory.SPELL, 5210, 1, ItemUpgradePath.NONE, "Homeward");
        put(spells, EquipmentCategory.SPELL, 5300, 1, ItemUpgradePath.NONE, "Force");
        put(spells, EquipmentCategory.SPELL, 5310, 1, ItemUpgradePath.NONE, "Wrath of the Gods");
        put(spells, EquipmentCategory.SPELL, 5320, 1, ItemUpgradePath.NONE, "Emit Force");
        put(spells, EquipmentCategory.SPELL, 5400, 1, ItemUpgradePath.NONE, "Seek Guidance");
        put(spells, EquipmentCategory.SPELL, 5500, 1, ItemUpgradePath.NONE, "Lightning Spear");
        put(spells, EquipmentCategory.SPELL, 5510, 1, ItemUpgradePath.NONE, "Great Lightning Spear");
        put(spells, EquipmentCategory.SPELL, 5520, 1, ItemUpgradePath.NONE, "Sunlight Spear");
        put(spells, EquipmentCategory.SPELL, 5600, 1, ItemUpgradePath.NONE, "Magic Barrier");
        put(spells, EquipmentCategory.SPELL, 5610, 1, ItemUpgradePath.NONE, "Great Magic Barrier");
        put(spells, EquipmentCategory.SPELL, 5700, 1, ItemUpgradePath.NONE, "Karmic Justice");
        put(spells, EquipmentCategory.SPELL, 5800, 1, ItemUpgradePath.NONE, "Tranquil Walk of Peace");
        put(spells, EquipmentCategory.SPELL, 5810, 1, ItemUpgradePath.NONE, "Vow of Silence");
        put(spells, EquipmentCategory.SPELL, 5900, 1, ItemUpgradePath.NONE, "Sunlight Blade");
        put(spells, EquipmentCategory.SPELL, 5910, 1, ItemUpgradePath.NONE, "Darkmoon Blade");

        put(rings, EquipmentCategory.RING, 100, 1, ItemUpgradePath.NONE, "Havel's Ring");
        put(rings, EquipmentCategory.RING, 101, 1, ItemUpgradePath.NONE, "Red Tearstone Ring");
        put(rings, EquipmentCategory.RING, 102, 1, ItemUpgradePath.NONE, "Darkmoon Blade Covenant Ring");
        put(rings, EquipmentCategory.RING, 103, 1, ItemUpgradePath.NONE, "Cat Covenant Ring");
        put(rings, EquipmentCategory.RING, 104, 1, ItemUpgradePath.NONE, "Cloranthy Ring");
        put(rings, EquipmentCategory.RING, 105, 1, ItemUpgradePath.NONE, "Flame Stoneplate Ring");
        put(rings, EquipmentCategory.RING, 106, 1, ItemUpgradePath.NONE, "Thunder Stoneplate Ring");
        put(rings, EquipmentCategory.RING, 107, 1, ItemUpgradePath.NONE, "Spell Stoneplate Ring");
        put(rings, EquipmentCategory.RING, 108, 1, ItemUpgradePath.NONE, "Speckled Stoneplate Ring");
        put(rings, EquipmentCategory.RING, 109, 1, ItemUpgradePath.NONE, "Bloodbite Ring");
        put(rings, EquipmentCategory.RING, 110, 1, ItemUpgradePath.NONE, "Poisonbite Ring");
        put(rings, EquipmentCategory.RING, 111, 1, ItemUpgradePath.NONE, "Tiny Being's Ring");
        put(rings, EquipmentCategory.RING, 113, 1, ItemUpgradePath.NONE, "Cursebite Ring");
        put(rings, EquipmentCategory.RING, 114, 1, ItemUpgradePath.NONE, "White Seance Ring");
        put(rings, EquipmentCategory.RING, 115, 1, ItemUpgradePath.NONE, "Bellowing Dragoncrest Ring");
        put(rings, EquipmentCategory.RING, 116, 1, ItemUpgradePath.NONE, "Dusk Crown Ring");
        put(rings, EquipmentCategory.RING, 117, 1, ItemUpgradePath.NONE, "Hornet Ring");
        put(rings, EquipmentCategory.RING, 119, 1, ItemUpgradePath.NONE, "Hawk Ring");
        put(rings, EquipmentCategory.RING, 120, 1, ItemUpgradePath.NONE, "Ring of Steel Protection");
        put(rings, EquipmentCategory.RING, 121, 1, ItemUpgradePath.NONE, "Covetous Gold Serpent Ring");
        put(rings, EquipmentCategory.RING, 122, 1, ItemUpgradePath.NONE, "Covetous Silver Serpent Ring");
        put(rings, EquipmentCategory.RING, 123, 1, ItemUpgradePath.NONE, "Slumbering Dragoncrest Ring");
        put(rings, EquipmentCategory.RING, 124, 1, ItemUpgradePath.NONE, "Ring of Fog");
        put(rings, EquipmentCategory.RING, 125, 1, ItemUpgradePath.NONE, "Rusted Iron Ring");
        put(rings, EquipmentCategory.RING, 126, 1, ItemUpgradePath.NONE, "Ring of Sacrifice");
        put(rings, EquipmentCategory.RING, 127, 1, ItemUpgradePath.NONE, "Rare Ring of Sacrifice");
        put(rings, EquipmentCategory.RING, 128, 1, ItemUpgradePath.NONE, "Dark Wood Grain Ring");
        put(rings, EquipmentCategory.RING, 130, 1, ItemUpgradePath.NONE, "Ring of the Sun Princess");
        put(rings, EquipmentCategory.RING, 137, 1, ItemUpgradePath.NONE, "Old Witch's Ring");
        put(rings, EquipmentCategory.RING, BASE_ITEM_ID_RING_COVENANT_OF_ARTORIAS, 1, ItemUpgradePath.NONE, "Covenant of Artorias");
        put(rings, EquipmentCategory.RING, BASE_ITEM_ID_RING_ORANGE_CHARRED, 1, ItemUpgradePath.NONE, "Orange Charred Ring");
        put(rings, EquipmentCategory.RING, 141, 1, ItemUpgradePath.NONE, "Lingering Dragoncrest Ring");
        put(rings, EquipmentCategory.RING, 142, 1, ItemUpgradePath.NONE, "Ring of the Evil Eye");
        put(rings, EquipmentCategory.RING, 143, 1, ItemUpgradePath.NONE, "Ring of Favor and Protection");
        put(rings, EquipmentCategory.RING, 144, 1, ItemUpgradePath.NONE, "Leo Ring");
        put(rings, EquipmentCategory.RING, 145, 1, ItemUpgradePath.NONE, "East Wood Grain Ring");
        put(rings, EquipmentCategory.RING, 146, 1, ItemUpgradePath.NONE, "Wolf Ring");
        put(rings, EquipmentCategory.RING, 147, 1, ItemUpgradePath.NONE, "Blue Tearstone Ring");
        put(rings, EquipmentCategory.RING, 148, 1, ItemUpgradePath.NONE, "Ring of the Sun's Firstborn");
        put(rings, EquipmentCategory.RING, 149, 1, ItemUpgradePath.NONE, "Darkmoon Seance Ring");
        put(rings, EquipmentCategory.RING, 150, 1, ItemUpgradePath.NONE, "Calamity Ring");

        ARMOR_BY_BASE_ID = Map.copyOf(armor);
        MELEE_WEAPON_BY_BASE_ID = Map.copyOf(melee);
        RANGED_WEAPON_BY_BASE_ID = Map.copyOf(ranged);
        SHIELD_BY_BASE_ID = Map.copyOf(shield);
        SPELL_TOOL_BY_BASE_ID = Map.copyOf(spellTools);
        SPELL_BY_BASE_ID = Map.copyOf(spells);
        RING_BY_BASE_ID = Map.copyOf(rings);
    }

    private EquipmentDefinitionTables() {}

    private static void put(
            final Map<Integer, BaseEquipmentDefinition> map,
            final EquipmentCategory category,
            final int baseItemId,
            final int stackLimit,
            final ItemUpgradePath upgradePath,
            final String displayName
    ) {
        map.put(
                baseItemId,
                new BaseEquipmentDefinition(baseItemId, stackLimit, upgradePath, category, displayName));
    }

    public static Map<Integer, BaseEquipmentDefinition> byCategory(final EquipmentCategory category) {
        return switch (category) {
            case ARMOR -> ARMOR_BY_BASE_ID;
            case MELEE_WEAPON -> MELEE_WEAPON_BY_BASE_ID;
            case RANGED_WEAPON -> RANGED_WEAPON_BY_BASE_ID;
            case SHIELD -> SHIELD_BY_BASE_ID;
            case SPELL_TOOL -> SPELL_TOOL_BY_BASE_ID;
            case SPELL -> SPELL_BY_BASE_ID;
            case RING -> RING_BY_BASE_ID;
        };
    }

    public static Optional<BaseEquipmentDefinition> find(
            final int baseItemId,
            final EquipmentCategory category
    ) {
        return switch (category) {
            case ARMOR -> Optional.ofNullable(ARMOR_BY_BASE_ID.get(baseItemId));
            case MELEE_WEAPON -> Optional.ofNullable(MELEE_WEAPON_BY_BASE_ID.get(baseItemId));
            case RANGED_WEAPON -> Optional.ofNullable(RANGED_WEAPON_BY_BASE_ID.get(baseItemId));
            case SHIELD -> Optional.ofNullable(SHIELD_BY_BASE_ID.get(baseItemId));
            case SPELL_TOOL -> Optional.ofNullable(SPELL_TOOL_BY_BASE_ID.get(baseItemId));
            case SPELL -> Optional.ofNullable(SPELL_BY_BASE_ID.get(baseItemId));
            case RING -> Optional.ofNullable(RING_BY_BASE_ID.get(baseItemId));
        };
    }
}
